# Generated by Django 4.2.28 on 2026-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date_rdv"]},
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Marque"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="city",
            field=models.CharField(
                db_index=True, default="Yaoundé", max_length=100, verbose_name="Ville"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("Essence", "Essence"),
                    ("Diesel", "Diesel"),
                    ("Hybride", "Hybride"),
                    ("Electrique", "Électrique"),
                ],
                db_index=True,
                default="Essence",
                max_length=20,
                verbose_name="Carburant",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, verbose_name="Prix"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("Vendu", "Vendu"),
                    ("En attente", "En attente de validation"),
                ],
                db_index=True,
                default="En attente",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(db_index=True, verbose_name="Année"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["status", "price"], name="idx_status_price"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_status_created"
            ),
        ),
    ]
